-- ============================================================================
-- APPLY_VISA_ENQUIRIES.sql — Dubai Visa enquiries for the Wicket portal
--
-- ► RUN THIS IN THE SUPABASE SQL EDITOR (Dashboard → SQL Editor → New query,
--   paste the whole file, Run). It is fully idempotent — safe to run again.
--
-- What it creates:
--   1) public.visa_enquiries — one row per public "Apply for Dubai Visa" form
--      submission (all 5 steps + management fields). Reference numbers like
--      #VQ-1042 are auto-generated by a trigger, same approach as order numbers.
--   2) RLS: ADMIN ONLY may read/update/delete. Anonymous may INSERT a fresh
--      'new' enquiry (the public form) but can never read anything back.
--      Employees and customers have NO access at all.
--   3) A PRIVATE storage bucket 'visa-documents' (PDF/JPG/PNG, max 10MB per
--      file). Only admin can read (the portal serves short-lived signed URLs).
--      Public uploads happen exclusively through the portal's API route using
--      the service-role key — there is deliberately NO anonymous storage
--      policy, so nobody can push files into the bucket directly.
-- ============================================================================


-- ============================================================================
-- 0) DEPENDENCY HELPER (idempotent re-create, identical to the live definition)
-- ============================================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;


-- ============================================================================
-- 1) TABLE — everything the public 5-step Dubai visa form collects
-- ============================================================================
create table if not exists public.visa_enquiries (
  id uuid primary key default gen_random_uuid(),

  -- Human reference "#VQ-1042" — trigger-filled on insert (see section 2).
  reference_number text,

  -- Step 1 — Visa & Travel
  more_than_one_person boolean not null default false,
  visa_type            text not null,
  purpose_of_visit     text,
  arrival_date         date,
  departure_date       date,
  planned_activities   text,

  -- Step 2 — Personal details
  first_name     text not null,
  last_name      text not null,
  other_names    text,
  date_of_birth  date,
  place_of_birth text,
  nationality    text,
  gender         text,
  marital_status text,
  email          text not null,
  phone          text not null,
  uk_address     text,

  -- Step 3 — Passport & UK visa
  passport_type            text,
  passport_number          text,
  passport_issue_date      date,
  passport_expiry_date     date,
  issuing_country          text,
  uk_visa_brp_ref          text,
  uk_visa_start_date       date,
  uk_visa_expiry_date      date,
  previously_visited_uae   boolean not null default false,
  previous_uae_visa_number text,

  -- Step 4 — Employment & background
  occupation               text,
  employer_name            text,
  job_title                text,
  employer_address         text,
  refused_entry_uae        boolean not null default false,
  criminal_conviction      boolean not null default false,
  who_covers_costs         text,
  preferred_contact_method text not null default 'email',

  -- Step 5 — Documents & notes
  additional_notes text,
  -- Uploaded document references: [{ "path", "name", "size", "type" }, …]
  -- (paths inside the private 'visa-documents' bucket; signed server-side)
  documents jsonb not null default '[]'::jsonb,

  -- Management (admin-only via RLS)
  status text not null default 'new',
  -- Timestamped internal notes: [{ "id", "body", "created_at" }, …]
  admin_notes jsonb not null default '[]'::jsonb,

  -- SHA-256 of the submitter's IP — powers server-side rate limiting in the
  -- portal's API route. Never the raw address.
  ip_hash text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.visa_enquiries drop constraint if exists visa_enquiries_status_check;
alter table public.visa_enquiries
  add constraint visa_enquiries_status_check
  check (status in ('new', 'contacted', 'in_progress', 'completed', 'closed'));

alter table public.visa_enquiries drop constraint if exists visa_enquiries_contact_check;
alter table public.visa_enquiries
  add constraint visa_enquiries_contact_check
  check (preferred_contact_method in ('email', 'phone', 'whatsapp'));

-- Query paths used by the admin tab + API rate limiter.
create index if not exists visa_enquiries_created_at_idx on public.visa_enquiries (created_at desc);
create index if not exists visa_enquiries_status_idx     on public.visa_enquiries (status);
create index if not exists visa_enquiries_ip_hash_idx    on public.visa_enquiries (ip_hash, created_at desc);


-- ============================================================================
-- 2) REFERENCE NUMBER — "#VQ-1042", auto-filled by trigger (same pattern as
--    orders' order_number). Sequential so references stay short and readable;
--    anonymous users can never read rows back, so sequences leak nothing.
-- ============================================================================
create sequence if not exists public.visa_enquiry_ref_seq start with 1042;

create or replace function public.tg_set_visa_reference()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.reference_number is null or new.reference_number = '' then
    new.reference_number := '#VQ-' || nextval('public.visa_enquiry_ref_seq')::text;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_visa_reference on public.visa_enquiries;
create trigger trg_set_visa_reference
  before insert on public.visa_enquiries
  for each row execute function public.tg_set_visa_reference();

create unique index if not exists visa_enquiries_reference_key
  on public.visa_enquiries (reference_number);

-- Keep updated_at fresh on every admin edit (status / notes).
create or replace function public.tg_touch_visa_enquiry()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_visa_enquiry on public.visa_enquiries;
create trigger trg_touch_visa_enquiry
  before update on public.visa_enquiries
  for each row execute function public.tg_touch_visa_enquiry();


-- ============================================================================
-- 3) RLS — admin-only management; anonymous insert-only for the public form
-- ============================================================================
alter table public.visa_enquiries enable row level security;

-- Admin: full read/update/delete (and insert, though normally unused).
drop policy if exists visa_enquiries_admin_all on public.visa_enquiries;
create policy visa_enquiries_admin_all on public.visa_enquiries
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Public form: anonymous INSERT only. No select/update/delete policy exists
-- for anon, so nothing can ever be read back with the anon key. The check
-- pins management fields so a submitter can't seed status or notes.
drop policy if exists visa_enquiries_anon_insert on public.visa_enquiries;
create policy visa_enquiries_anon_insert on public.visa_enquiries
  for insert to anon
  with check (
    status = 'new'
    and admin_notes = '[]'::jsonb
  );

-- NOTE: employees/customers (authenticated, non-admin) match NO policy → no access.


-- ============================================================================
-- 4) STORAGE — private 'visa-documents' bucket (PDF/JPG/PNG, 10MB cap).
--    Uploads run through the portal API (service role) only; admin reads via
--    short-lived signed URLs. No anonymous storage policy on purpose.
-- ============================================================================
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'visa-documents',
  'visa-documents',
  false,
  10485760, -- 10MB per file
  array['application/pdf', 'image/jpeg', 'image/png']
)
on conflict (id) do update
  set public = false,
      file_size_limit = 10485760,
      allowed_mime_types = array['application/pdf', 'image/jpeg', 'image/png'];

drop policy if exists visa_documents_admin_read on storage.objects;
create policy visa_documents_admin_read on storage.objects
  for select to authenticated
  using (bucket_id = 'visa-documents' and public.is_admin());

drop policy if exists visa_documents_admin_delete on storage.objects;
create policy visa_documents_admin_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'visa-documents' and public.is_admin());

-- ============================================================================
-- Done. Reload the portal — the admin "Visa Queries" tab and the public
-- /api/visa-enquiry endpoint are now fully live.
-- ============================================================================
