-- ============================================================================
-- APPLY_PARENTS_TICKETS.sql — "Parents Tickets" lead capture for the Wicket portal
--
-- ► RUN THIS IN THE SUPABASE SQL EDITOR (Dashboard → SQL Editor → New query,
--   paste the whole file, Run). It is fully idempotent — safe to run again.
--
-- What this is:
--   A BASIC lead-capture feature. Two sides of the same board submit a short
--   text form on the public homepage:
--     • traveller  — someone flying who can keep an eye on / assist a parent
--     • requester  — someone who needs a companion for their parent's journey
--   Admin reads the leads and contacts people manually. No ID checks, no OTP,
--   no matching engine, no dashboards, no payments — text only.
--
-- What it creates:
--   1) public.parent_ticket_enquiries — one row per public submission (shared
--      fields + the side-specific fields + management fields). Reference
--      numbers like #PT-1001 are auto-generated by a trigger, same approach as
--      order numbers and #VQ-… visa references.
--   2) RLS: ADMIN ONLY may read/update/delete. Anonymous may INSERT a fresh
--      'new' lead (the public form) but can never read anything back.
--      Employees and customers have NO access at all.
-- ============================================================================


-- ============================================================================
-- 0) DEPENDENCY HELPER (idempotent re-create, identical to the live definition)
-- ============================================================================
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;


-- ============================================================================
-- 1) TABLE — everything the public Parents Tickets form collects
-- ============================================================================
create table if not exists public.parent_ticket_enquiries (
  id uuid primary key default gen_random_uuid(),

  -- Human reference "#PT-1001" — trigger-filled on insert (see section 2).
  reference_number text,

  -- Which side of the board submitted this lead.
  enquiry_type text not null,

  -- Shared fields (both sides)
  full_name     text not null,
  email         text not null,
  phone         text not null,
  from_location text not null,
  to_location   text not null,
  travel_date   date,
  airline       text,
  languages     text,
  notes         text,

  -- Traveller-side fields (nullable — filled only when enquiry_type='traveller')
  assistance_offered text,      -- what help they can give
  parents_can_help   int,       -- how many parents they could accompany
  fee_amount         numeric,   -- fee they'd charge (0–100)

  -- Requester-side fields (nullable — filled only when enquiry_type='requester')
  parent_name       text,
  parent_age        int,
  relationship      text,       -- relationship to the traveller/parent
  assistance_needed text,       -- what help the parent needs
  mobility_needs    text,       -- mobility / accessibility notes
  offer_amount      numeric,    -- amount they'd offer (0–100)

  -- Management (admin-only via RLS)
  status text not null default 'new',
  -- Timestamped internal notes: [{ "id", "body", "created_at" }, …]
  admin_notes jsonb not null default '[]'::jsonb,

  -- SHA-256 of the submitter's IP — powers server-side rate limiting in the
  -- portal's API route. Never the raw address.
  ip_hash text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.parent_ticket_enquiries drop constraint if exists parent_ticket_enquiries_type_check;
alter table public.parent_ticket_enquiries
  add constraint parent_ticket_enquiries_type_check
  check (enquiry_type in ('traveller', 'requester'));

alter table public.parent_ticket_enquiries drop constraint if exists parent_ticket_enquiries_status_check;
alter table public.parent_ticket_enquiries
  add constraint parent_ticket_enquiries_status_check
  check (status in ('new', 'contacted', 'matched', 'closed'));

-- Fee / offer are small companion amounts — pin them to a sane 0–100 range.
alter table public.parent_ticket_enquiries drop constraint if exists parent_ticket_enquiries_fee_check;
alter table public.parent_ticket_enquiries
  add constraint parent_ticket_enquiries_fee_check
  check (fee_amount is null or (fee_amount >= 0 and fee_amount <= 100));

alter table public.parent_ticket_enquiries drop constraint if exists parent_ticket_enquiries_offer_check;
alter table public.parent_ticket_enquiries
  add constraint parent_ticket_enquiries_offer_check
  check (offer_amount is null or (offer_amount >= 0 and offer_amount <= 100));

-- Query paths used by the admin tab + API rate limiter.
create index if not exists parent_ticket_enquiries_created_at_idx on public.parent_ticket_enquiries (created_at desc);
create index if not exists parent_ticket_enquiries_status_idx     on public.parent_ticket_enquiries (status);
create index if not exists parent_ticket_enquiries_type_idx       on public.parent_ticket_enquiries (enquiry_type);
create index if not exists parent_ticket_enquiries_ip_hash_idx    on public.parent_ticket_enquiries (ip_hash, created_at desc);


-- ============================================================================
-- 2) REFERENCE NUMBER — "#PT-1001", auto-filled by trigger (same pattern as
--    orders' order_number and #VQ-… visa references). Sequential so references
--    stay short and readable; anonymous users can never read rows back, so
--    sequences leak nothing.
-- ============================================================================
create sequence if not exists public.parent_ticket_ref_seq start with 1001;

create or replace function public.tg_set_parent_ticket_reference()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  if new.reference_number is null or new.reference_number = '' then
    new.reference_number := '#PT-' || nextval('public.parent_ticket_ref_seq')::text;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_set_parent_ticket_reference on public.parent_ticket_enquiries;
create trigger trg_set_parent_ticket_reference
  before insert on public.parent_ticket_enquiries
  for each row execute function public.tg_set_parent_ticket_reference();

create unique index if not exists parent_ticket_enquiries_reference_key
  on public.parent_ticket_enquiries (reference_number);

-- Keep updated_at fresh on every admin edit (status / notes).
create or replace function public.tg_touch_parent_ticket_enquiry()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists trg_touch_parent_ticket_enquiry on public.parent_ticket_enquiries;
create trigger trg_touch_parent_ticket_enquiry
  before update on public.parent_ticket_enquiries
  for each row execute function public.tg_touch_parent_ticket_enquiry();


-- ============================================================================
-- 3) RLS — admin-only management; anonymous insert-only for the public form
-- ============================================================================
alter table public.parent_ticket_enquiries enable row level security;

-- Admin: full read/update/delete (and insert, though normally unused).
drop policy if exists parent_ticket_enquiries_admin_all on public.parent_ticket_enquiries;
create policy parent_ticket_enquiries_admin_all on public.parent_ticket_enquiries
  for all to authenticated
  using (public.is_admin())
  with check (public.is_admin());

-- Public form: anonymous INSERT only. No select/update/delete policy exists
-- for anon, so nothing can ever be read back with the anon key. The check
-- pins management fields so a submitter can't seed status or notes.
drop policy if exists parent_ticket_enquiries_anon_insert on public.parent_ticket_enquiries;
create policy parent_ticket_enquiries_anon_insert on public.parent_ticket_enquiries
  for insert to anon
  with check (
    status = 'new'
    and admin_notes = '[]'::jsonb
  );

-- NOTE: employees/customers (authenticated, non-admin) match NO policy → no access.

-- ============================================================================
-- Done. Reload the portal — the admin "Parents Tickets" tab and the public
-- /api/parent-ticket endpoint are now fully live.
-- ============================================================================
